stacks:
  - flexible
regions:
  - eu-west-1
deployments:
  recipes:
    type: autoscaling
    parameters:
      bucket: composer-dist
    dependencies:
      - cloudformation
  cloudformation:
    type: cloud-formation
    app: recipes
    parameters:
      amiTags:
        Recipe: editorial-tools-xenial-java8
        AmigoStage: PROD
        BuiltBy: amigo
      amiEncrypted: true
      templatePath: recipes.cfn.yaml
      prependStackToCloudFormationStackName: false
  RecipesDynamoTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: recipes
      AttributeDefinitions:
      - AttributeName: path
        AttributeType: S
      - AttributeName: recipeId
        AttributeType: N
      KeySchema:
      - AttributeName: path
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      GlobalSecondaryIndexes:
      - IndexName: recipeId
        KeySchema:
        - AttributeName: recipeId
          KeyType: HASH
        Projection:
          ProjectionType: ALL
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1