#!/usr/bin/env bash

set -e

npm ci
#npm test # This should be re-enabled as soon as client app is fixed
#npm run lint # This should be re-enabled as soon as client app is fixed
npm run build

(
  cd cdk
  npm ci
  npm run lint
  npm test
  npm run synth
)
