name: CI
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
jobs:
  js-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version-file: '.node-version'
      - run: ./scripts/ci-js
  sbt-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '8'
      - run: ./scripts/ci-sbt
