name: CI
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
jobs:
  js-build:
    runs-on: ubuntu-latest
    steps:
      - name: Set BUILD_NUMBER environment variable
        run: |
          LAST_TEAMCITY_BUILD=215
          echo "BUILD_NUMBER=$(( $GITHUB_RUN_NUMBER + $LAST_TEAMCITY_BUILD ))" >> $GITHUB_ENV
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version-file: '.node-version'
      - run: ./scripts/ci-js
  sbt-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '8'
      - run: ./scripts/ci-sbt

      # Fetch AWS credentials, allowing us to upload to Riff-Raff (well, S3)
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.GU_RIFF_RAFF_ROLE_ARN }}
          aws-region: eu-west-1

      # Upload our build artifacts to Riff-Raff (well, S3)
      - uses: guardian/actions-riff-raff@v2
        with:
          projectName: editorial-tools::recipes
          buildNumber: ${{ env.BUILD_NUMBER }}
          configPath: riff-raff.yaml
          contentDirectories: |
            cloudformation:
              - cloudformation.yaml
            recipes:
              - target/recipes_1.0-SNAPSHOT_all.deb
